/**
 * IEC60870-5-104-simulator.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IecDoublePointValueEnumDto } from './iecDoublePointValueEnumDto';


export interface DoublePointValueDto { 
    value?: IecDoublePointValueEnumDto;
}
export namespace DoublePointValueDto {
}


