/**
 * IEC60870-5-104-simulator.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Iec104DataTypes = 'ASDU_TYPEUNDEF' | 'M_SP_NA_1' | 'M_SP_TA_1' | 'M_DP_NA_1' | 'M_DP_TA_1' | 'M_ST_NA_1' | 'M_ST_TA_1' | 'M_BO_NA_1' | 'M_BO_TA_1' | 'M_ME_NA_1' | 'M_ME_TA_1' | 'M_ME_NB_1' | 'M_ME_TB_1' | 'M_ME_NC_1' | 'M_ME_TC_1' | 'M_IT_NA_1' | 'M_IT_TA_1' | 'M_EP_TA_1' | 'M_EP_TB_1' | 'M_EP_TC_1' | 'M_PS_NA_1' | 'M_ME_ND_1' | 'ASDU_TYPE_22_29' | 'M_SP_TB_1' | 'M_DP_TB_1' | 'M_ST_TB_1' | 'M_BO_TB_1' | 'M_ME_TD_1' | 'M_ME_TE_1' | 'M_ME_TF_1' | 'M_IT_TB_1' | 'M_EP_TD_1' | 'M_EP_TE_1' | 'M_EP_TF_1' | 'ASDU_TYPE_41_44' | 'C_SC_NA_1' | 'C_DC_NA_1' | 'C_RC_NA_1' | 'C_SE_NA_1' | 'C_SE_NB_1' | 'C_SE_NC_1' | 'C_BO_NA_1' | 'ASDU_TYPE_52_57' | 'C_SC_TA_1' | 'C_DC_TA_1' | 'C_RC_TA_1' | 'C_SE_TA_1' | 'C_SE_TB_1' | 'C_SE_TC_1' | 'C_BO_TA_1' | 'ASDU_TYPE_65_69' | 'M_EI_NA_1' | 'ASDU_TYPE_71_99' | 'C_IC_NA_1' | 'C_CI_NA_1' | 'C_RD_NA_1' | 'C_CS_NA_1' | 'C_TS_NA_1' | 'C_RP_NA_1' | 'C_CD_NA_1' | 'C_TS_TA_1' | 'ASDU_TYPE_108_109' | 'P_ME_NA_1' | 'P_ME_NB_1' | 'P_ME_NC_1' | 'P_AC_NA_1' | 'ASDU_TYPE_114_119' | 'F_FR_NA_1' | 'F_SR_NA_1' | 'F_SC_NA_1' | 'F_LS_NA_1' | 'F_FA_NA_1' | 'F_SG_NA_1' | 'F_DR_TA_1' | 'ASDU_TYPE_127_255';

export const Iec104DataTypes = {

    AsduTypeundef: 'ASDU_TYPEUNDEF' as Iec104DataTypes,

    MSpNa1: 'M_SP_NA_1' as Iec104DataTypes,

    MSpTa1: 'M_SP_TA_1' as Iec104DataTypes,

    MDpNa1: 'M_DP_NA_1' as Iec104DataTypes,

    MDpTa1: 'M_DP_TA_1' as Iec104DataTypes,

    MStNa1: 'M_ST_NA_1' as Iec104DataTypes,

    MStTa1: 'M_ST_TA_1' as Iec104DataTypes,

    MBoNa1: 'M_BO_NA_1' as Iec104DataTypes,

    MBoTa1: 'M_BO_TA_1' as Iec104DataTypes,

    MMeNa1: 'M_ME_NA_1' as Iec104DataTypes,

    MMeTa1: 'M_ME_TA_1' as Iec104DataTypes,

    MMeNb1: 'M_ME_NB_1' as Iec104DataTypes,

    MMeTb1: 'M_ME_TB_1' as Iec104DataTypes,

    MMeNc1: 'M_ME_NC_1' as Iec104DataTypes,

    MMeTc1: 'M_ME_TC_1' as Iec104DataTypes,

    MItNa1: 'M_IT_NA_1' as Iec104DataTypes,

    MItTa1: 'M_IT_TA_1' as Iec104DataTypes,

    MEpTa1: 'M_EP_TA_1' as Iec104DataTypes,

    MEpTb1: 'M_EP_TB_1' as Iec104DataTypes,

    MEpTc1: 'M_EP_TC_1' as Iec104DataTypes,

    MPsNa1: 'M_PS_NA_1' as Iec104DataTypes,

    MMeNd1: 'M_ME_ND_1' as Iec104DataTypes,

    AsduType2229: 'ASDU_TYPE_22_29' as Iec104DataTypes,

    MSpTb1: 'M_SP_TB_1' as Iec104DataTypes,

    MDpTb1: 'M_DP_TB_1' as Iec104DataTypes,

    MStTb1: 'M_ST_TB_1' as Iec104DataTypes,

    MBoTb1: 'M_BO_TB_1' as Iec104DataTypes,

    MMeTd1: 'M_ME_TD_1' as Iec104DataTypes,

    MMeTe1: 'M_ME_TE_1' as Iec104DataTypes,

    MMeTf1: 'M_ME_TF_1' as Iec104DataTypes,

    MItTb1: 'M_IT_TB_1' as Iec104DataTypes,

    MEpTd1: 'M_EP_TD_1' as Iec104DataTypes,

    MEpTe1: 'M_EP_TE_1' as Iec104DataTypes,

    MEpTf1: 'M_EP_TF_1' as Iec104DataTypes,

    AsduType4144: 'ASDU_TYPE_41_44' as Iec104DataTypes,

    CScNa1: 'C_SC_NA_1' as Iec104DataTypes,

    CDcNa1: 'C_DC_NA_1' as Iec104DataTypes,

    CRcNa1: 'C_RC_NA_1' as Iec104DataTypes,

    CSeNa1: 'C_SE_NA_1' as Iec104DataTypes,

    CSeNb1: 'C_SE_NB_1' as Iec104DataTypes,

    CSeNc1: 'C_SE_NC_1' as Iec104DataTypes,

    CBoNa1: 'C_BO_NA_1' as Iec104DataTypes,

    AsduType5257: 'ASDU_TYPE_52_57' as Iec104DataTypes,

    CScTa1: 'C_SC_TA_1' as Iec104DataTypes,

    CDcTa1: 'C_DC_TA_1' as Iec104DataTypes,

    CRcTa1: 'C_RC_TA_1' as Iec104DataTypes,

    CSeTa1: 'C_SE_TA_1' as Iec104DataTypes,

    CSeTb1: 'C_SE_TB_1' as Iec104DataTypes,

    CSeTc1: 'C_SE_TC_1' as Iec104DataTypes,

    CBoTa1: 'C_BO_TA_1' as Iec104DataTypes,

    AsduType6569: 'ASDU_TYPE_65_69' as Iec104DataTypes,

    MEiNa1: 'M_EI_NA_1' as Iec104DataTypes,

    AsduType7199: 'ASDU_TYPE_71_99' as Iec104DataTypes,

    CIcNa1: 'C_IC_NA_1' as Iec104DataTypes,

    CCiNa1: 'C_CI_NA_1' as Iec104DataTypes,

    CRdNa1: 'C_RD_NA_1' as Iec104DataTypes,

    CCsNa1: 'C_CS_NA_1' as Iec104DataTypes,

    CTsNa1: 'C_TS_NA_1' as Iec104DataTypes,

    CRpNa1: 'C_RP_NA_1' as Iec104DataTypes,

    CCdNa1: 'C_CD_NA_1' as Iec104DataTypes,

    CTsTa1: 'C_TS_TA_1' as Iec104DataTypes,

    AsduType108109: 'ASDU_TYPE_108_109' as Iec104DataTypes,

    PMeNa1: 'P_ME_NA_1' as Iec104DataTypes,

    PMeNb1: 'P_ME_NB_1' as Iec104DataTypes,

    PMeNc1: 'P_ME_NC_1' as Iec104DataTypes,

    PAcNa1: 'P_AC_NA_1' as Iec104DataTypes,

    AsduType114119: 'ASDU_TYPE_114_119' as Iec104DataTypes,

    FFrNa1: 'F_FR_NA_1' as Iec104DataTypes,

    FSrNa1: 'F_SR_NA_1' as Iec104DataTypes,

    FScNa1: 'F_SC_NA_1' as Iec104DataTypes,

    FLsNa1: 'F_LS_NA_1' as Iec104DataTypes,

    FFaNa1: 'F_FA_NA_1' as Iec104DataTypes,

    FSgNa1: 'F_SG_NA_1' as Iec104DataTypes,

    FDrTa1: 'F_DR_TA_1' as Iec104DataTypes,

    AsduType127255: 'ASDU_TYPE_127_255' as Iec104DataTypes
};

