/**
 * IEC60870-5-104-simulator.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationMode } from './simulationMode';
import { IecAddress } from './iecAddress';
import { Iec104DataTypes } from './iec104DataTypes';


export interface Iec104DataPoint { 
    id?: string | null;
    address?: IecAddress;
    iec104DataType?: Iec104DataTypes;
    value?: object;
    mode?: SimulationMode;
    initString?: string | null;
}
export namespace Iec104DataPoint {
}


