/**
 * IEC60870-5-104-simulator.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type IecDoublePointValueEnumDto = 'INTERMEDIATE' | 'false' | 'true' | 'INDETERMINATE';

export const IecDoublePointValueEnumDto = {

    Intermediate: 'INTERMEDIATE' as IecDoublePointValueEnumDto,

    False: 'false' as IecDoublePointValueEnumDto,

    True: 'true' as IecDoublePointValueEnumDto,

    Indeterminate: 'INDETERMINATE' as IecDoublePointValueEnumDto
};

