/**
 * IEC60870-5-104-simulator.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SimulationState = 'Stopped' | 'Running';

export const SimulationState = {

    Stopped: 'Stopped' as SimulationState,

    Running: 'Running' as SimulationState
};

