/**
 * IEC60870-5-104-simulator.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationMode } from './simulationMode';
import { Iec104DataTypes } from './iec104DataTypes';


export interface Iec104DataPointDto { 
    id?: string | null;
    stationaryAddress: number;
    objectAddress: number;
    iec104DataType: Iec104DataTypes;
    value?: string | null;
    mode?: SimulationMode;
}
export namespace Iec104DataPointDto {
}


