name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build --target final --tag iec60870-5-104-simulator:$(date +%s) .

    - name: Build  the test Docker image
      run: DOCKER_BUILDKIT=1 docker build --pull --target test -t iec60870-5-104-simulatortest:$(date +%s) .

    - name: Run tests in Docker image
      run: docker run -t iec60870-5-104-simulatortest:$(date +%s)
